# Ref: https://istio.io/latest/docs/ambient/install/helm/
---
commonLabels:
  domain: mesh
  phase: install

repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts

releases:
  - name: istio-base
    namespace: istio-system
    createNamespace: true
    chart: istio/base
    version: ~1.26.0
    wait: true
    hooks:
      - events:
          - "presync"
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml"

  - name: istiod
    namespace: istio-system
    createNamespace: true
    chart: istio/istiod
    version: ~1.26.0
    wait: true
    needs:
      - istio-base
    values:
      - ./values/mesh-base/istiod.yaml

  - name: istio-cni
    namespace: istio-system
    createNamespace: true
    chart: istio/cni
    version: ~1.26.0
    wait: true
    needs:
      - istiod
    values:
      - ./values/mesh-base/istio-cni.yaml

  - name: ztunnel
    namespace: istio-system
    createNamespace: true
    chart: istio/ztunnel
    version: ~1.26.0
    wait: true
    needs:
      - istio-cni
