---
networking:
  addAWaypoint: true

authorization:
  addAuthorizations: true
  jwtRules:
    - issuer: "http://keycloak-app.keycloak:8000/realms/there-is-no-point"
      jwksUri: "http://keycloak-app.keycloak.svc.cluster.local:8000/realms/there-is-no-point/protocol/openid-connect/certs"
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/product-page/sa/product-page-app
            requestPrincipals:
              - "*"
      to:
        - operation:
            methods:
              - GET
            paths:
              - "/details/{*}"
      when:
        - key: request.auth.claims[realm_access][roles]
          values:
            - details:read
