---
networking:
  addAWaypoint: true

authorization:
  addAuthorizations: true
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/reviews/sa/reviews-app
      to:
        - operation:
            methods:
              - GET
            paths:
              - "/ratings/{*}"
