---
networking:
  addAWaypoint: true

  rules:
    - backendRefs:
        - name: reviews-app-v1
          port: 8000
          weight: 60
        - name: reviews-app-v2
          port: 8000
          weight: 30
        - name: reviews-app-v3
          port: 8000
          weight: 10

authorization:
  addAuthorizations: true
  jwtRules:
    - issuer: "http://keycloak-app.keycloak:8000/realms/there-is-no-point"
      jwksUri: "http://keycloak-app.keycloak.svc.cluster.local:8000/realms/there-is-no-point/protocol/openid-connect/certs"
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/product-page/sa/product-page-app
            requestPrincipals:
              - "*"
      to:
        - operation:
            methods:
              - GET
            paths:
              - "/reviews/{*}"
      when:
        - key: request.auth.claims[realm_access][roles]
          values:
            - reviews:read
