---
image:
  #repository: istio/examples-bookinfo-productpage-v1
  repository: registry.localhost:5000/istio/examples-bookinfo-productpage-v1
  tag: "1.20.3"
containerPort: 9080

podSecurityContext:
  fsGroup: 2000
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
livenessProbe:
  httpGet:
    path: /health
    port: http
readinessProbe:
  httpGet:
    path: /health
    port: http
volumes:
  - name: tmp
    emptyDir: {}
volumeMounts:
  - name: tmp
    mountPath: /tmp
env:
  - name: REVIEWS_HOSTNAME
    value: "reviews-mesh.reviews"
  - name: REVIEWS_SERVICE_PORT
    value: "8000"
  - name: DETAILS_HOSTNAME
    value: "details-mesh.details"
  - name: DETAILS_SERVICE_PORT
    value: "8000"
